version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: >
      sh -c "./docker/wait-for-it.sh ${DB_HOST}:${DB_PORT} -- poetry run uvicorn app.main:app --host 0.0.0.0 --reload --port ${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./app:/project/app"
    env_file:
      - .env
    container_name: fastapi_app
    depends_on:
      - database
    stdin_open: true
    tty: true

  database:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: fastapi_database
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - ${DB_PORT}:3306
    volumes:
      - fastapi_db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: fastapi_adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  fastapi_db:
